name: 'Make Test'
on:
  push:
    branches:
      - master
      - maint-3.9
      - gh-ci-make-test2
  pull_request:
    branches:
      - master
      - maint-3.9
jobs:
  check-formatting:
    name: Check C++ Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gnuradio/clang-format-lint-action@v0.5-4
      with:
        source: '.'
        exclude: './volk'
        extensions: 'h,hpp,cpp,cc'
  # All of these shall depend on the formatting check (needs: check-formatting)
  ubuntu-20_04:
    name: Ubuntu 20.04
    needs: check-formatting
    runs-on: ubuntu-latest
    container:
      image: 'gnuradio/ci-ubuntu-20.04-3.9:0.3'
      volumes:
        - build_data:/build
      options: --cpus 2
    steps:
    - uses: actions/checkout@v2
      name: Checkout Project
    - name: CMake
      run: 'cd /build && cmake ${GITHUB_WORKSPACE}'
    - name: Make
      run: 'cd /build && make -j2'
    - name: Make Test
      run: 'cd /build && ctest --output-on-failure -E qa_uhd|qa_uncaught_exception|qa_header_payload_demux'
